/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPresencasRouteImport } from './routes/_authenticated/presencas'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedAdminCasasRouteImport } from './routes/_authenticated/_admin/casas'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/_admin/eventos'
import { Route as AuthenticatedAdminFuncoesRouteImport } from './routes/_authenticated/_admin/funcoes'
import { Route as AuthenticatedAdminInstrumentosRouteImport } from './routes/_authenticated/_admin/instrumentos'
import { Route as AuthenticatedAdminVinculosRouteImport } from './routes/_authenticated/_admin/vinculos'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPresencasRoute = AuthenticatedPresencasRouteImport.update({
  id: '/_authenticated/presencas',
  path: '/presencas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/_authenticated/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCasasRoute = AuthenticatedAdminCasasRouteImport.update({
  id: '/_authenticated/_admin/casas',
  path: '/casas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/_authenticated/_admin/eventos',
    path: '/eventos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminFuncoesRoute =
  AuthenticatedAdminFuncoesRouteImport.update({
    id: '/_authenticated/_admin/funcoes',
    path: '/funcoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminInstrumentosRoute =
  AuthenticatedAdminInstrumentosRouteImport.update({
    id: '/_authenticated/_admin/instrumentos',
    path: '/instrumentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminVinculosRoute =
  AuthenticatedAdminVinculosRouteImport.update({
    id: '/_authenticated/_admin/vinculos',
    path: '/vinculos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/presencas': typeof AuthenticatedPresencasRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/': typeof AuthenticatedIndexRoute
  '/casas': typeof AuthenticatedAdminCasasRoute
  '/eventos': typeof AuthenticatedAdminEventosRoute
  '/funcoes': typeof AuthenticatedAdminFuncoesRoute
  '/instrumentos': typeof AuthenticatedAdminInstrumentosRoute
  '/vinculos': typeof AuthenticatedAdminVinculosRoute
}
export interface FileRoutesByTo {
  '/presencas': typeof AuthenticatedPresencasRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/': typeof AuthenticatedIndexRoute
  '/casas': typeof AuthenticatedAdminCasasRoute
  '/eventos': typeof AuthenticatedAdminEventosRoute
  '/funcoes': typeof AuthenticatedAdminFuncoesRoute
  '/instrumentos': typeof AuthenticatedAdminInstrumentosRoute
  '/vinculos': typeof AuthenticatedAdminVinculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/presencas': typeof AuthenticatedPresencasRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/casas': typeof AuthenticatedAdminCasasRoute
  '/_authenticated/_admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/_admin/funcoes': typeof AuthenticatedAdminFuncoesRoute
  '/_authenticated/_admin/instrumentos': typeof AuthenticatedAdminInstrumentosRoute
  '/_authenticated/_admin/vinculos': typeof AuthenticatedAdminVinculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/presencas'
    | '/relatorio'
    | '/'
    | '/casas'
    | '/eventos'
    | '/funcoes'
    | '/instrumentos'
    | '/vinculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/presencas'
    | '/relatorio'
    | '/'
    | '/casas'
    | '/eventos'
    | '/funcoes'
    | '/instrumentos'
    | '/vinculos'
  id:
    | '__root__'
    | '/_authenticated/presencas'
    | '/_authenticated/relatorio'
    | '/_authenticated/'
    | '/_authenticated/_admin/casas'
    | '/_authenticated/_admin/eventos'
    | '/_authenticated/_admin/funcoes'
    | '/_authenticated/_admin/instrumentos'
    | '/_authenticated/_admin/vinculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedPresencasRoute: typeof AuthenticatedPresencasRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminCasasRoute: typeof AuthenticatedAdminCasasRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminFuncoesRoute: typeof AuthenticatedAdminFuncoesRoute
  AuthenticatedAdminInstrumentosRoute: typeof AuthenticatedAdminInstrumentosRoute
  AuthenticatedAdminVinculosRoute: typeof AuthenticatedAdminVinculosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/presencas': {
      id: '/_authenticated/presencas'
      path: '/presencas'
      fullPath: '/presencas'
      preLoaderRoute: typeof AuthenticatedPresencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/casas': {
      id: '/_authenticated/_admin/casas'
      path: '/casas'
      fullPath: '/casas'
      preLoaderRoute: typeof AuthenticatedAdminCasasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/eventos': {
      id: '/_authenticated/_admin/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/funcoes': {
      id: '/_authenticated/_admin/funcoes'
      path: '/funcoes'
      fullPath: '/funcoes'
      preLoaderRoute: typeof AuthenticatedAdminFuncoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/instrumentos': {
      id: '/_authenticated/_admin/instrumentos'
      path: '/instrumentos'
      fullPath: '/instrumentos'
      preLoaderRoute: typeof AuthenticatedAdminInstrumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/vinculos': {
      id: '/_authenticated/_admin/vinculos'
      path: '/vinculos'
      fullPath: '/vinculos'
      preLoaderRoute: typeof AuthenticatedAdminVinculosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedPresencasRoute: AuthenticatedPresencasRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminCasasRoute: AuthenticatedAdminCasasRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminFuncoesRoute: AuthenticatedAdminFuncoesRoute,
  AuthenticatedAdminInstrumentosRoute: AuthenticatedAdminInstrumentosRoute,
  AuthenticatedAdminVinculosRoute: AuthenticatedAdminVinculosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
