/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedPresencasRouteImport } from './routes/_authenticated/presencas'
import { Route as AuthenticatedAdminCasasRouteImport } from './routes/_authenticated/_admin/casas'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/_admin/eventos'
import { Route as AuthenticatedAdminFuncoesRouteImport } from './routes/_authenticated/_admin/funcoes'
import { Route as AuthenticatedAdminInstrumentosRouteImport } from './routes/_authenticated/_admin/instrumentos'
import { Route as AuthenticatedAdminRelatorioRouteImport } from './routes/_authenticated/_admin/relatorio'
import { Route as AuthenticatedAdminSetoresRouteImport } from './routes/_authenticated/_admin/setores'
import { Route as AuthenticatedAdminTreinamentoRouteImport } from './routes/_authenticated/_admin/treinamento'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/_admin/usuarios'
import { Route as AuthenticatedAdminVinculosRouteImport } from './routes/_authenticated/_admin/vinculos'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresencasRoute = AuthenticatedPresencasRouteImport.update({
  id: '/presencas',
  path: '/presencas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCasasRoute = AuthenticatedAdminCasasRouteImport.update({
  id: '/casas',
  path: '/casas',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFuncoesRoute =
  AuthenticatedAdminFuncoesRouteImport.update({
    id: '/funcoes',
    path: '/funcoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInstrumentosRoute =
  AuthenticatedAdminInstrumentosRouteImport.update({
    id: '/instrumentos',
    path: '/instrumentos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRelatorioRoute =
  AuthenticatedAdminRelatorioRouteImport.update({
    id: '/relatorio',
    path: '/relatorio',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSetoresRoute =
  AuthenticatedAdminSetoresRouteImport.update({
    id: '/setores',
    path: '/setores',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTreinamentoRoute =
  AuthenticatedAdminTreinamentoRouteImport.update({
    id: '/treinamento',
    path: '/treinamento',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVinculosRoute =
  AuthenticatedAdminVinculosRouteImport.update({
    id: '/vinculos',
    path: '/vinculos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/presencas': typeof AuthenticatedPresencasRoute
  '/casas': typeof AuthenticatedAdminCasasRoute
  '/eventos': typeof AuthenticatedAdminEventosRoute
  '/funcoes': typeof AuthenticatedAdminFuncoesRoute
  '/instrumentos': typeof AuthenticatedAdminInstrumentosRoute
  '/relatorio': typeof AuthenticatedAdminRelatorioRoute
  '/setores': typeof AuthenticatedAdminSetoresRoute
  '/treinamento': typeof AuthenticatedAdminTreinamentoRoute
  '/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/vinculos': typeof AuthenticatedAdminVinculosRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/presencas': typeof AuthenticatedPresencasRoute
  '/casas': typeof AuthenticatedAdminCasasRoute
  '/eventos': typeof AuthenticatedAdminEventosRoute
  '/funcoes': typeof AuthenticatedAdminFuncoesRoute
  '/instrumentos': typeof AuthenticatedAdminInstrumentosRoute
  '/relatorio': typeof AuthenticatedAdminRelatorioRoute
  '/setores': typeof AuthenticatedAdminSetoresRoute
  '/treinamento': typeof AuthenticatedAdminTreinamentoRoute
  '/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/vinculos': typeof AuthenticatedAdminVinculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/presencas': typeof AuthenticatedPresencasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/casas': typeof AuthenticatedAdminCasasRoute
  '/_authenticated/_admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/_admin/funcoes': typeof AuthenticatedAdminFuncoesRoute
  '/_authenticated/_admin/instrumentos': typeof AuthenticatedAdminInstrumentosRoute
  '/_authenticated/_admin/relatorio': typeof AuthenticatedAdminRelatorioRoute
  '/_authenticated/_admin/setores': typeof AuthenticatedAdminSetoresRoute
  '/_authenticated/_admin/treinamento': typeof AuthenticatedAdminTreinamentoRoute
  '/_authenticated/_admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/_admin/vinculos': typeof AuthenticatedAdminVinculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/presencas'
    | '/casas'
    | '/eventos'
    | '/funcoes'
    | '/instrumentos'
    | '/relatorio'
    | '/setores'
    | '/treinamento'
    | '/usuarios'
    | '/vinculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/presencas'
    | '/casas'
    | '/eventos'
    | '/funcoes'
    | '/instrumentos'
    | '/relatorio'
    | '/setores'
    | '/treinamento'
    | '/usuarios'
    | '/vinculos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/presencas'
    | '/_authenticated/'
    | '/_authenticated/_admin/casas'
    | '/_authenticated/_admin/eventos'
    | '/_authenticated/_admin/funcoes'
    | '/_authenticated/_admin/instrumentos'
    | '/_authenticated/_admin/relatorio'
    | '/_authenticated/_admin/setores'
    | '/_authenticated/_admin/treinamento'
    | '/_authenticated/_admin/usuarios'
    | '/_authenticated/_admin/vinculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presencas': {
      id: '/_authenticated/presencas'
      path: '/presencas'
      fullPath: '/presencas'
      preLoaderRoute: typeof AuthenticatedPresencasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/casas': {
      id: '/_authenticated/_admin/casas'
      path: '/casas'
      fullPath: '/casas'
      preLoaderRoute: typeof AuthenticatedAdminCasasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/eventos': {
      id: '/_authenticated/_admin/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/funcoes': {
      id: '/_authenticated/_admin/funcoes'
      path: '/funcoes'
      fullPath: '/funcoes'
      preLoaderRoute: typeof AuthenticatedAdminFuncoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/instrumentos': {
      id: '/_authenticated/_admin/instrumentos'
      path: '/instrumentos'
      fullPath: '/instrumentos'
      preLoaderRoute: typeof AuthenticatedAdminInstrumentosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/relatorio': {
      id: '/_authenticated/_admin/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedAdminRelatorioRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/setores': {
      id: '/_authenticated/_admin/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof AuthenticatedAdminSetoresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/treinamento': {
      id: '/_authenticated/_admin/treinamento'
      path: '/treinamento'
      fullPath: '/treinamento'
      preLoaderRoute: typeof AuthenticatedAdminTreinamentoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/usuarios': {
      id: '/_authenticated/_admin/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/vinculos': {
      id: '/_authenticated/_admin/vinculos'
      path: '/vinculos'
      fullPath: '/vinculos'
      preLoaderRoute: typeof AuthenticatedAdminVinculosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCasasRoute: typeof AuthenticatedAdminCasasRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminFuncoesRoute: typeof AuthenticatedAdminFuncoesRoute
  AuthenticatedAdminInstrumentosRoute: typeof AuthenticatedAdminInstrumentosRoute
  AuthenticatedAdminRelatorioRoute: typeof AuthenticatedAdminRelatorioRoute
  AuthenticatedAdminSetoresRoute: typeof AuthenticatedAdminSetoresRoute
  AuthenticatedAdminTreinamentoRoute: typeof AuthenticatedAdminTreinamentoRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVinculosRoute: typeof AuthenticatedAdminVinculosRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCasasRoute: AuthenticatedAdminCasasRoute,
    AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
    AuthenticatedAdminFuncoesRoute: AuthenticatedAdminFuncoesRoute,
    AuthenticatedAdminInstrumentosRoute: AuthenticatedAdminInstrumentosRoute,
    AuthenticatedAdminRelatorioRoute: AuthenticatedAdminRelatorioRoute,
    AuthenticatedAdminSetoresRoute: AuthenticatedAdminSetoresRoute,
    AuthenticatedAdminTreinamentoRoute: AuthenticatedAdminTreinamentoRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminVinculosRoute: AuthenticatedAdminVinculosRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPresencasRoute: typeof AuthenticatedPresencasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPresencasRoute: AuthenticatedPresencasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
